export const GET_DISTRICTS = "GET_DISTRICTS";
export const GET_DISTRICTS_SUCCESS = "GET_DISTRICTS_SUCCESS";
export const GET_DISTRICTS_FAILURE = "GET_DISTRICTS_FAILURE";

export const GET_DISTRICT_DETAIL = "GET_DISTRICT_DETAIL";
export const GET_DISTRICT_DETAIL_SUCCESS = "GET_DISTRICT_DETAIL_SUCCESS";
export const GET_DISTRICT_DETAIL_FAILURE = "GET_DISTRICT_DETAIL_FAILURE";

export const SEARCH_DISTRICTS = "SEARCH_DISTRICTS";
export const SEARCH_DISTRICTS_SUCCESS = "SEARCH_DISTRICTS_SUCCESS";
export const SEARCH_DISTRICTS_FAILURE = "SEARCH_DISTRICTS_FAILURE";

export const ADD_DISTRICT = "ADD_DISTRICT";
export const ADD_DISTRICT_SUCCESS = "ADD_DISTRICT_SUCCESS";
export const ADD_DISTRICT_FAILURE = "ADD_DISTRICT_FAILURE";

export const DELETE_DISTRICT = "DELETE_DISTRICT";
export const DELETE_DISTRICT_SUCCESS = "DELETE_DISTRICT_SUCCESS";
export const DELETE_DISTRICT_FAILURE = "DELETE_DISTRICT_FAILURE";

export const UPDATE_DISTRICT = "UPDATE_DISTRICT";
export const UPDATE_DISTRICT_SUCCESS = "UPDATE_DISTRICT_SUCCESS";
export const UPDATE_DISTRICT_FAILURE = "UPDATE_DISTRICT_FAILURE";

export const GET_DISTRICTS_BY_PROVINCE = "GET_DISTRICTS_BY_PROVINCE";
export const GET_DISTRICTS_BY_PROVINCE_SUCCESS = "GET_DISTRICTS_BY_PROVINCE_SUCCESS";
export const GET_DISTRICTS_BY_PROVINCE_FAILURE = "GET_DISTRICTS_BY_PROVINCE_FAILURE";
