export const GET_PROVINCES = "GET_PROVINCES";
export const GET_PROVINCES_SUCCESS = "GET_PROVINCES_SUCCESS";
export const GET_PROVINCES_FAILURE = "GET_PROVINCES_FAILURE";

export const SEARCH_PROVINCES = "SEARCH_PROVINCES";
export const SEARCH_PROVINCES_SUCCESS = "SEARCH_PROVINCES_SUCCESS";
export const SEARCH_PROVINCES_FAILURE = "SEARCH_PROVINCES_FAILURE";

export const ADD_PROVINCE = "ADD_PROVINCE";
export const ADD_PROVINCE_SUCCESS = "ADD_PROVINCE_SUCCESS";
export const ADD_PROVINCE_FAILURE = "ADD_PROVINCE_FAILURE";

export const DELETE_PROVINCE = "DELETE_PROVINCE";
export const DELETE_PROVINCE_SUCCESS = "DELETE_PROVINCE_SUCCESS";
export const DELETE_PROVINCE_FAILURE = "DELETE_PROVINCE_FAILURE";

export const UPDATE_PROVINCE = "UPDATE_PROVINCE";
export const UPDATE_PROVINCE_SUCCESS = "UPDATE_PROVINCE_SUCCESS";
export const UPDATE_PROVINCE_FAILURE = "UPDATE_PROVINCE_FAILURE";