export const GET_WARDS = "GET_WARDS";
export const GET_WARDS_SUCCESS = "GET_WARDS_SUCCESS";
export const GET_WARDS_FAILURE = "GET_WARDS_FAILURE";

export const SEARCH_WARDS = "SEARCH_WARDS";
export const SEARCH_WARDS_SUCCESS = "SEARCH_WARDS_SUCCESS";
export const SEARCH_WARDS_FAILURE = "SEARCH_WARDS_FAILURE";

export const ADD_WARD = "ADD_WARD";
export const ADD_WARD_SUCCESS = "ADD_WARD_SUCCESS";
export const ADD_WARD_FAILURE = "ADD_WARD_FAILURE";

export const DELETE_WARD = "DELETE_WARD";
export const DELETE_WARD_SUCCESS = "DELETE_WARD_SUCCESS";
export const DELETE_WARD_FAILURE = "DELETE_WARD_FAILURE";

export const UPDATE_WARD = "UPDATE_WARD";
export const UPDATE_WARD_SUCCESS = "UPDATE_WARD_SUCCESS";
export const UPDATE_WARD_FAILURE = "UPDATE_WARD_FAILURE";

export const GET_WARDS_BY_DISTRICT = "GET_WARDS_BY_DISTRICT";
export const GET_WARDS_BY_DISTRICT_SUCCESS = "GET_WARDS_BY_DISTRICT_SUCCESS";
export const GET_WARDS_BY_DISTRICT_FAILURE = "GET_WARDS_BY_DISTRICT_FAILURE";
